from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file

#LLM
from langchain_groq import ChatGroq

# Prompt
from langchain_core.prompts import ChatPromptTemplate

# PDF Loading and chunking
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Embeddings and Vector Store
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

# RAG Chain builders
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains import create_retrieval_chain
#retrieval chain will go to vectorstore and retrieve relevant chunks based on the query and then combine it using the stuff_documents_chain and then pass it to the LLM for generating the answer.
# warnings
import warnings
warnings.filterwarnings("ignore",category=FutureWarning)
warnings.filterwarnings("ignore",category=UserWarning)  

#load secrets from .env file
load_dotenv()  # Load environment variables from .env file  

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

embeddings= HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")    

pdf_path = "data/aiml_concepts_master_guide.pdf"
loader = PyPDFLoader(pdf_path)
pages = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = text_splitter.split_documents(pages)

vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory="./chroma_db",collection_name="pdf_collection")

rag_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a helpful assistant that answers questions based ONLY on the provided context from pdf document.
    RULES:
    - Answer the question using only the information provided in the context.
    - Be concise and direct in your response.
    - If the context contains relevant information, provide a clear answer
    - use bullet points for listing multiple items.
    
    IMPORTANT: If the answer is NOT in the provided context, strictly say:
     " I don't know based on the provided document."
     Do NOT Make up or assume any information.
     
     CONTEXT: {context}
     """),
    ("human", "{input}")
])

documents_chain = create_stuff_documents_chain(llm, rag_prompt)

retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 3})  
# k=3 means it will retrieve the top 3 most relevant chunks from the vectorstore based on the query.
# search_kwargs={"k": 3} means it will retrieve the top 3 most relevant chunks from the vectorstore based on the query.  
# search_type="similarity" means it will use cosine similarity to find the most relevant chunks.

rag_chain = create_retrieval_chain(retriever, documents_chain)

#ask a question
question1 = "What is Linear Regression?"

response1 = rag_chain.invoke({"input": question1})    
print(response1["answer"]) # Print the answer generated by the RAG chain


question2 = "What is the recipe of chocolate cake?"

response2 = rag_chain.invoke({"input": question2})    
print(response2["answer"]) # Print the answer generated by the RAG chain